# Generated by Django 2.0.3 on 2018-03-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_attributetype_productvariance_productvarianceattribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvarianceattribute',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productvarianceattribute',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productvarianceattribute',
            name='sh_price',
        ),
        migrations.AddField(
            model_name='productvarianceattribute',
            name='size',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='productvarianceattribute',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
